export const UNSAFE_PEOPLE_ROOT_CASES = [
	{ label: "empty", root: "" },
	{ label: "whitespace-only", root: "   " },
	{ label: "backslash", root: "Second Brain\\People" },
	{ label: "less-than", root: "Second Brain/People<Archive" },
	{ label: "greater-than", root: "Second Brain/People>Archive" },
	{ label: "colon", root: "Second Brain/People:Archive" },
	{ label: "double quote", root: 'Second Brain/People"Archive' },
	{ label: "wikilink alias delimiter", root: "Second Brain/People|Archive" },
	{ label: "query delimiter", root: "Second Brain/People?Archive" },
	{ label: "asterisk", root: "Second Brain/People*Archive" },
	{ label: "opening bracket", root: "Second Brain/People[Archive" },
	{ label: "closing bracket", root: "Second Brain/People]Archive" },
	{ label: "heading delimiter", root: "Second Brain/People#Archive" },
	{ label: "block delimiter", root: "Second Brain/People^Archive" },
	{ label: "NUL control", root: "Second Brain/People\u0000Archive" },
	{ label: "unit-separator control", root: "Second Brain/People\u001fArchive" },
	{ label: "DEL control", root: "Second Brain/People\u007fArchive" },
	{ label: "absolute path", root: "/Second Brain/People" },
	{ label: "URL", root: "https://example.com/people" },
	{ label: "dot segment", root: "Second Brain/../People" },
	{ label: "double separator", root: "Second Brain//People" },
	{ label: "trailing slash", root: "Second Brain/People/" },
] as const;
