import { PLUGIN_DATA_SCHEMA_VERSION } from "../constants";
import { DEFAULT_RELATIONSHIP_ROLE_FORMAT } from "./relationship-presets";
import type { PeopleAtlasSettings } from "./types";

export const DEFAULT_SETTINGS: PeopleAtlasSettings = {
	schemaVersion: PLUGIN_DATA_SCHEMA_VERSION,
	peopleFolder: "People",
	contactMomentsFolder: "People/Contact moments",
	typeProperty: "type",
	personTypeValue: "person",
	relationshipTypeValue: "relationship",
	contactMomentTypeValue: "contact_moment",
	personTag: "person",
	personIdProperty: "person_id",
	nameProperty: "name",
	aliasesProperty: "aliases",
	organisationsProperty: "organisations",
	photoProperty: "photo",
	contactsProperty: "contacts",
	birthDateProperty: "birth_date",
	pronounsProperty: "pronouns",
	genderProperty: "gender",
	emailsProperty: "emails",
	phonesProperty: "phones",
	jobTitleProperty: "job_title",
	relationshipIdProperty: "relationship_id",
	relationshipFromProperty: "from",
	relationshipToProperty: "to",
	relationshipTypesProperty: "relationship_types",
	relationshipPresetProperty: "relationship_preset",
	relationshipFromRoleProperty: "from_role",
	relationshipToRoleProperty: "to_role",
	closenessProperty: "closeness",
	sinceProperty: "since",
	lastContactProperty: "last_contact",
	statusProperty: "status",
	contactMomentIdProperty: "contact_moment_id",
	contactMomentPeopleProperty: "people",
	contactMomentRelationshipProperty: "relationship",
	contactMomentOccurredOnProperty: "occurred_on",
	contactMomentChannelProperty: "channel",
	contactMomentSummaryProperty: "summary",
	contactMomentFollowUpOnProperty: "follow_up_on",
	contactMomentFollowUpStatusProperty: "follow_up_status",
	myPersonId: "",
	defaultCenterPersonId: "",
	enableBases: true,
	showLabels: true,
	showDiagnostics: true,
	relationshipRoleFormat: DEFAULT_RELATIONSHIP_ROLE_FORMAT,
	relationshipPresets: [],
	viewStates: {},
};
