import { PLUGIN_DATA_SCHEMA_VERSION } from "../constants";
import { DEFAULT_RELATIONSHIP_ROLE_FORMAT } from "./relationship-presets";
import type { PeopleAtlasSettings } from "./types";

export const DEFAULT_SETTINGS: PeopleAtlasSettings = {
	schemaVersion: PLUGIN_DATA_SCHEMA_VERSION,
	peopleFolder: "People",
	typeProperty: "type",
	personTypeValue: "person",
	relationshipTypeValue: "relationship",
	personTag: "person",
	personIdProperty: "person_id",
	nameProperty: "name",
	aliasesProperty: "aliases",
	organisationsProperty: "organisations",
	photoProperty: "photo",
	contactsProperty: "contacts",
	relationshipIdProperty: "relationship_id",
	relationshipFromProperty: "from",
	relationshipToProperty: "to",
	relationshipTypesProperty: "relationship_types",
	relationshipPresetProperty: "relationship_preset",
	relationshipFromRoleProperty: "from_role",
	relationshipToRoleProperty: "to_role",
	directionProperty: "direction",
	closenessProperty: "closeness",
	sinceProperty: "since",
	lastContactProperty: "last_contact",
	statusProperty: "status",
	defaultCenterPersonId: "",
	enableBases: true,
	showLabels: true,
	showDiagnostics: true,
	relationshipRoleFormat: DEFAULT_RELATIONSHIP_ROLE_FORMAT,
	relationshipPresets: [],
	viewStates: {},
};
