import type { AtlasViewState } from "./view-state";
import type { RelationshipPreset } from "./relationship-presets";

export interface PeopleAtlasSettings {
	schemaVersion: number;
	peopleRootFolder: string;
	typeProperty: string;
	personTypeValue: string;
	relationshipTypeValue: string;
	contactMomentTypeValue: string;
	personTag: string;
	personIdProperty: string;
	nameProperty: string;
	aliasesProperty: string;
	organisationsProperty: string;
	photoProperty: string;
	contactsProperty: string;
	birthDateProperty: string;
	pronounsProperty: string;
	genderProperty: string;
	emailsProperty: string;
	phonesProperty: string;
	jobTitleProperty: string;
	relationshipIdProperty: string;
	relationshipFromProperty: string;
	relationshipToProperty: string;
	relationshipTypesProperty: string;
	relationshipPresetProperty: string;
	relationshipFromRoleProperty: string;
	relationshipToRoleProperty: string;
	closenessProperty: string;
	sinceProperty: string;
	lastContactProperty: string;
	statusProperty: string;
	contactMomentIdProperty: string;
	contactMomentPeopleProperty: string;
	contactMomentRelationshipProperty: string;
	contactMomentOccurredOnProperty: string;
	contactMomentChannelProperty: string;
	contactMomentSummaryProperty: string;
	contactMomentFollowUpOnProperty: string;
	contactMomentFollowUpStatusProperty: string;
	myPersonId: string;
	defaultCenterPersonId: string;
	enableBases: boolean;
	showLabels: boolean;
	showDiagnostics: boolean;
	relationshipRoleFormat: string;
	relationshipPresets: RelationshipPreset[];
	viewStates: Record<string, AtlasViewState>;
}
